from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
import zipfile
from pathlib import Path

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:  # pragma: no cover - handled at runtime.
    Image = None
    ImageDraw = None
    ImageFont = None


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PROJECTS_ROOT = Path(r"C:\Unreal Engine Projects\FAB-ASSET-PACKS")
DEFAULT_UE_ROOT = Path(r"C:\Program Files\Epic Games\UE_5.3")
TARGET_ENGINE_ASSOCIATION = "5.3"
TARGET_COVER_SIZE = (1980, 1920)
MAX_COVER_BYTES = 3 * 1024 * 1024
EXCLUDED_ARCHIVE_DIRS = {".vs", "Binaries", "DerivedDataCache", "Intermediate", "Saved"}
ALLOWED_TEXTURE_NAMES = {
    *(f"T_Photo_{index:02d}_D" for index in range(1, 7)),
    *(f"T_Picture_{index:02d}_D" for index in range(1, 12)),
}
ALLOWED_SOURCE_SIZES = {(1024, 1024), (2048, 2048)}


def load_config(path: Path) -> dict:
    with path.open("r", encoding="utf-8-sig") as handle:
        config = json.load(handle)
    config["_config_path"] = str(path.resolve())
    return config


def resolve_repo_path(value: str | os.PathLike[str]) -> Path:
    path = Path(value)
    if not path.is_absolute():
        path = REPO_ROOT / path
    return path.resolve()


def project_root(config: dict) -> Path:
    root = Path(config.get("projects_root") or DEFAULT_PROJECTS_ROOT)
    return root / config["project_name"]


def ensure_clean_destination(path: Path, force: bool) -> None:
    if not path.exists():
        return
    if not force:
        raise SystemExit(f"Destination already exists: {path}. Use --force to replace it.")
    shutil.rmtree(path)


def read_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def write_json(path: Path, data: dict) -> None:
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        json.dump(data, handle, ensure_ascii=False, indent="\t")
        handle.write("\n")


def set_project_plugins(project_data: dict) -> None:
    desired = {
        "PythonScriptPlugin": True,
        "EditorScriptingUtilities": True,
        "ModelingToolsEditorMode": False,
        "MeshModelingToolset": False,
        "ModelingToolsEditorModeEditorOnly": False,
    }
    existing = {plugin.get("Name"): plugin for plugin in project_data.get("Plugins", []) if plugin.get("Name")}
    for name, enabled in desired.items():
        item = existing.get(name) or {"Name": name}
        item["Enabled"] = enabled
        existing[name] = item
    project_data["Plugins"] = sorted(existing.values(), key=lambda item: item["Name"])


def validate_texture_reimports(config: dict) -> None:
    reimports = config.get("texture_reimports", [])
    if not reimports:
        return

    for item in reimports:
        asset = item["asset"]
        name = asset.rsplit("/", 1)[-1]
        if name not in ALLOWED_TEXTURE_NAMES:
            allowed = ", ".join(sorted(ALLOWED_TEXTURE_NAMES))
            raise SystemExit(f"Refusing to reimport non-picture texture {asset!r}. Allowed texture assets: {allowed}")

        source = Path(item["source"])
        if not source.exists():
            raise SystemExit(f"Source image does not exist: {source}")
        require_pillow()
        with Image.open(source) as image:
            if image.size not in ALLOWED_SOURCE_SIZES:
                raise SystemExit(
                    f"Source image must be 1024x1024 or 2048x2048, got {image.size[0]}x{image.size[1]}: {source}"
                )


def create_project(args: argparse.Namespace) -> None:
    config = load_config(args.config)
    template_zip = resolve_repo_path(config["template_zip"])
    dest = project_root(config)
    ensure_clean_destination(dest, args.force)
    dest.parent.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(template_zip, "r") as archive:
        archive.extractall(dest)

    old_project_files = list(dest.glob("*.uproject"))
    if not old_project_files:
        raise SystemExit(f"No .uproject found after extracting {template_zip}")

    old_uproject = old_project_files[0]
    new_uproject = dest / f"{config['project_name']}.uproject"
    if old_uproject != new_uproject:
        old_uproject.rename(new_uproject)

    project_data = read_json(new_uproject)
    project_data["EngineAssociation"] = TARGET_ENGINE_ASSOCIATION
    project_data.setdefault("FileVersion", 3)
    project_data.setdefault("Category", "")
    project_data["Description"] = f"FAB asset pack generated by FAB MCP Pipeliner: {config['pack_title']}"
    set_project_plugins(project_data)
    write_json(new_uproject, project_data)

    print(f"Created project: {dest}")
    print(f"Project file: {new_uproject}")
    if config.get("template_pack_folder") and config.get("template_pack_folder") != config["pack_folder"]:
        print("Template content folder will be renamed inside Unreal:")
        print(f"  /Game/{config['template_pack_folder']} -> /Game/{config['pack_folder']}")


def require_pillow() -> None:
    if Image is None:
        raise SystemExit("Pillow is required. Install with: pip install -r requirements.txt")


def load_font(size: int):
    if ImageFont is None:
        return None
    candidates = [
        r"C:\Windows\Fonts\arialbd.ttf",
        r"C:\Windows\Fonts\arial.ttf",
    ]
    for candidate in candidates:
        if Path(candidate).exists():
            return ImageFont.truetype(candidate, size=size)
    return ImageFont.load_default()


def draw_centered(draw, box: tuple[int, int, int, int], text: str, font, fill: tuple[int, int, int]) -> None:
    left, top, right, bottom = box
    bbox = draw.multiline_textbbox((0, 0), text, font=font, align="center", spacing=8)
    text_w = bbox[2] - bbox[0]
    text_h = bbox[3] - bbox[1]
    x = left + (right - left - text_w) / 2
    y = top + (bottom - top - text_h) / 2
    draw.multiline_text((x, y), text, font=font, fill=fill, align="center", spacing=8)


def process_showcase(args: argparse.Namespace) -> None:
    require_pillow()
    input_path = Path(args.input)
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with Image.open(input_path) as source:
        source = source.convert("RGB")
        canvas = Image.new("RGB", TARGET_COVER_SIZE, (18, 18, 18))
        title_h = 230
        footer_h = 180
        image_box = (0, title_h, TARGET_COVER_SIZE[0], TARGET_COVER_SIZE[1] - footer_h)
        box_w = image_box[2] - image_box[0]
        box_h = image_box[3] - image_box[1]

        scale = max(box_w / source.width, box_h / source.height)
        resized = source.resize((round(source.width * scale), round(source.height * scale)), Image.LANCZOS)
        crop_left = max(0, (resized.width - box_w) // 2)
        crop_top = max(0, (resized.height - box_h) // 2)
        cropped = resized.crop((crop_left, crop_top, crop_left + box_w, crop_top + box_h))
        canvas.paste(cropped, (image_box[0], image_box[1]))

    draw = ImageDraw.Draw(canvas)
    title_font = load_font(88)
    footer_font = load_font(58)
    draw.rectangle((0, 0, TARGET_COVER_SIZE[0], 230), fill=(20, 18, 16))
    draw.rectangle((0, TARGET_COVER_SIZE[1] - 180, TARGET_COVER_SIZE[0], TARGET_COVER_SIZE[1]), fill=(20, 18, 16))
    draw_centered(draw, (80, 18, TARGET_COVER_SIZE[0] - 80, 218), args.title, title_font, (246, 238, 220))
    draw_centered(
        draw,
        (80, TARGET_COVER_SIZE[1] - 160, TARGET_COVER_SIZE[0] - 80, TARGET_COVER_SIZE[1] - 20),
        args.resolution_label,
        footer_font,
        (246, 238, 220),
    )

    quality = 95
    while True:
        canvas.save(output_path, format="JPEG", quality=quality, optimize=True, progressive=True)
        if output_path.stat().st_size <= MAX_COVER_BYTES or quality <= 72:
            break
        quality -= 3

    if output_path.stat().st_size > MAX_COVER_BYTES:
        raise SystemExit(f"Cover is still larger than 3 MB: {output_path.stat().st_size} bytes")

    print(f"Cover written: {output_path}")
    print(f"Size: {TARGET_COVER_SIZE[0]}x{TARGET_COVER_SIZE[1]}, bytes: {output_path.stat().st_size}, jpeg quality: {quality}")


def ue_command(args: argparse.Namespace) -> None:
    config = load_config(args.config)
    validate_texture_reimports(config)
    ue_root = Path(config.get("ue_root") or DEFAULT_UE_ROOT)
    editor_cmd = ue_root / "Engine" / "Binaries" / "Win64" / "UnrealEditor-Cmd.exe"
    project_file = project_root(config) / f"{config['project_name']}.uproject"
    script = REPO_ROOT / "scripts" / "ue_fab_pipeline.py"
    command = [
        str(editor_cmd),
        str(project_file),
        "-unattended",
        "-nop4",
        "-nosplash",
        "-run=pythonscript",
        f"-script={script}",
        f"-fab_config={Path(config['_config_path']).resolve()}",
    ]
    print(" ".join(f'"{part}"' if " " in part else part for part in command))


def validate_project(args: argparse.Namespace) -> None:
    config = load_config(args.config)
    validate_texture_reimports(config)
    root = project_root(config)
    project_file = root / f"{config['project_name']}.uproject"
    if not project_file.exists():
        raise SystemExit(f"Missing project file: {project_file}")

    project_data = read_json(project_file)
    engine = str(project_data.get("EngineAssociation", ""))
    if engine != TARGET_ENGINE_ASSOCIATION:
        raise SystemExit(f"Expected EngineAssociation {TARGET_ENGINE_ASSOCIATION}, got {engine!r}")

    content = root / "Content"
    if not content.exists():
        raise SystemExit(f"Missing Content folder: {content}")
    dirs = sorted(p.name for p in content.iterdir() if p.is_dir())
    expected = config["pack_folder"]
    if dirs != [expected]:
        raise SystemExit(f"Content must contain only {expected!r}; found {dirs}")

    config_dir = root / "Config"
    if not config_dir.exists():
        raise SystemExit(f"Missing Config folder: {config_dir}")

    print(f"Validation passed: {root}")


def should_archive(path: Path, project: Path) -> bool:
    rel_parts = path.relative_to(project).parts
    return not any(part in EXCLUDED_ARCHIVE_DIRS for part in rel_parts)


def zip_project(args: argparse.Namespace) -> None:
    config = load_config(args.config)
    root = project_root(config)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)

    include_roots = ["Content", "Config", "Plugins"]
    project_file = root / f"{config['project_name']}.uproject"
    if not project_file.exists():
        raise SystemExit(f"Missing project file: {project_file}")

    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=6) as archive:
        archive.write(project_file, project_file.name)
        for name in include_roots:
            folder = root / name
            if not folder.exists():
                continue
            for file in folder.rglob("*"):
                if file.is_file() and should_archive(file, root):
                    archive.write(file, file.relative_to(root).as_posix())

    print(f"Zip written: {output}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="FAB asset pack host-side pipeline tools.")
    sub = parser.add_subparsers(required=True)

    create = sub.add_parser("create-project", help="Create a UE project from the template zip.")
    create.add_argument("--config", type=Path, required=True)
    create.add_argument("--force", action="store_true")
    create.set_defaults(func=create_project)

    cover = sub.add_parser("process-showcase", help="Normalize and compress the FAB cover image.")
    cover.add_argument("--input", required=True)
    cover.add_argument("--output", required=True)
    cover.add_argument("--title", required=True)
    cover.add_argument("--resolution-label", required=True)
    cover.set_defaults(func=process_showcase)

    ue = sub.add_parser("ue-command", help="Print the UE 5.3 command for in-editor automation.")
    ue.add_argument("--config", type=Path, required=True)
    ue.set_defaults(func=ue_command)

    validate = sub.add_parser("validate-project", help="Validate pack project structure.")
    validate.add_argument("--config", type=Path, required=True)
    validate.set_defaults(func=validate_project)

    zipper = sub.add_parser("zip-project", help="Zip a validated project without UE cache folders.")
    zipper.add_argument("--config", type=Path, required=True)
    zipper.add_argument("--output", required=True)
    zipper.set_defaults(func=zip_project)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    args.func(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
